pipelines:
    - name: "pipeline"
      steps:
          - name: "Step1"
            hostname: "server1"
            contactURL: "/job"
            method: "post"
            payload:
                dataSource: "https://path/of/the/datasource"
                dataDestination: "https://this/can/be/a/template/{job_id}"
          - name: "Step2"
            hostname: "server2"
            contactURL: "/job"
            method: "get"