pipelines:
    - name: "pipeline"
      steps:
          - name: "Step1"
            hostname: "Server1"
            contactURL: "http://{hostname}/job/{job_id}"
            method: "post"
            payload:
                dataSource: "https://ExternalServer/download/{job_id}.yaml"
          - name: "Step2"
            hostname: "Server2:8000"
            contactURL: "http://{hostname}/job/{job_id}"
            method: "post"
            payload:
                dataSource: "https://ExternalServer/download/{job_id}.json"